import { Link } from "wouter";
import { Mail, MessageCircle, Phone, ShieldAlert } from "lucide-react";

const LOGO = "/manus-storage/sou-eletricista-logo_a1bfc7b7.png";

export default function Contactos() {
  return <div className="min-h-screen bg-[#f8fbff] text-[#12213a] dark:bg-[#07111f] dark:text-white"><header className="border-b border-blue-100 bg-white/90 dark:border-white/10 dark:bg-[#07111f]/90"><div className="container flex h-20 items-center justify-between"><Link href="/" className="flex items-center gap-3"><img src={LOGO} alt="Sou Eletricista" className="h-12 w-12 rounded-full object-cover" /><span className="font-display font-black text-[#0b45ad] dark:text-white">Sou Eletricista</span></Link><Link href="/" className="text-sm font-bold text-[#0b45ad] dark:text-[#ffd326]">Voltar à Home</Link></div></header><main className="container py-16"><div className="max-w-3xl"><p className="eyebrow">Estamos disponíveis</p><h1 className="section-title mt-4">Fale com a nossa equipa.</h1><p className="mt-5 text-lg leading-8 text-slate-600 dark:text-slate-300">Tem dúvidas sobre a formação, inscrição ou pagamento? Envie uma mensagem e a Coordenação responderá.</p></div><div className="mt-12 grid gap-6 md:grid-cols-3"><ContactCard icon={Mail} label="E-mail" value="souelectricista@gmail.com" href="mailto:souelectricista@gmail.com" /><ContactCard icon={Phone} label="Telefone / WhatsApp" value="+244 955 104 495" href="tel:+244955104495" /><ContactCard icon={ShieldAlert} label="Emergência" value="+244 947 227 693" href="tel:+244947227693" /></div><a href="https://wa.me/244955104495" target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-3 rounded-full bg-[#13a85b] px-6 py-3.5 font-extrabold text-white"><MessageCircle className="h-5 w-5" /> Falar pelo WhatsApp</a><section className="mt-20 rounded-[2rem] border border-blue-100 bg-white p-8 dark:border-white/10 dark:bg-white/5"><p className="eyebrow">Inscrições e pagamentos</p><h2 className="mt-3 font-display text-3xl font-black">Os dados de pagamento ficam protegidos no formulário.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600 dark:text-slate-300">Para sua segurança, as coordenadas de pagamento não são publicadas nesta página. Elas aparecem apenas na etapa de pagamento do formulário de inscrição, antes do carregamento do comprovativo.</p><Link href="/inscricao" className="mt-6 inline-flex rounded-full bg-[#f3bd08] px-6 py-3 font-extrabold text-[#082d70]">Ir para inscrição</Link></section><div className="mt-12 rounded-[2rem] bg-[#0b45ad] p-8 text-white"><p className="eyebrow text-[#ffd326]">Atendimento direto</p><h2 className="mt-3 font-display text-2xl font-black">Estamos prontos para ajudar.</h2><p className="mt-3 max-w-xl text-blue-100">Escolha o canal que preferir e fale com a nossa equipa sobre a sua formação.</p></div></main></div>;
}

function ContactCard({ icon: Icon, label, value, href }: { icon: any; label: string; value: string; href: string }) { return <a href={href} className="rounded-3xl border border-blue-100 bg-white p-6 transition hover:-translate-y-1 hover:shadow-lg dark:border-white/10 dark:bg-white/5"><Icon className="h-8 w-8 text-[#e0a900]" /><p className="mt-6 text-sm text-slate-500">{label}</p><p className="mt-2 font-bold text-[#0b45ad] dark:text-white">{value}</p></a>; }
