import { Award, Medal, Trophy } from "lucide-react";
import { trpc } from "@/lib/trpc";

export function StudentRankingPanel({ accessCode }: { accessCode: string }) {
  const ranking = trpc.student.ranking.useQuery({ accessCode }, { enabled: Boolean(accessCode), staleTime: 30000, refetchOnWindowFocus: false });
  const data = ranking.data;
  return <section className="mt-8 rounded-[2rem] border border-blue-100 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/5 sm:p-8">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Destaques da turma</p><h2 className="mt-2 font-display text-2xl font-black">Ranking de aproveitamento</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500 dark:text-slate-300">Classificação dos melhores resultados do seu curso e mês de aprovação. Outros nomes são apresentados de forma abreviada.</p></div><Trophy className="h-10 w-10 text-[#e0a900]" /></div>
    {ranking.isLoading && <p className="mt-8 text-sm text-slate-500" role="status">A carregar a classificação…</p>}
    {ranking.isError && <p className="mt-8 text-sm text-red-600" role="alert">Não foi possível carregar o ranking. Tente novamente.</p>}
    {data && <><div className="mt-6 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-blue-50 px-3 py-2 text-[#0b45ad] dark:bg-blue-500/10 dark:text-blue-100">{data.courseTitle}</span><span className="rounded-full bg-amber-50 px-3 py-2 text-amber-800 dark:bg-amber-500/10 dark:text-amber-200">Turma {data.cohort}</span></div>{data.students.length ? <ol className="mt-6 space-y-3">{data.students.map(student => <li key={student.position} className={`flex items-center justify-between gap-3 rounded-2xl border p-4 ${student.isMe ? "border-[#f3bd08] bg-amber-50 dark:bg-amber-500/10" : "border-blue-100 bg-[#f8fbff] dark:border-white/10 dark:bg-white/5"}`}><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#0b45ad] font-black text-white">{student.position <= 3 ? <Medal className="h-5 w-5 text-[#ffd326]" /> : student.position}</span><div className="min-w-0"><p className="truncate font-bold">{student.displayName}</p><p className="text-xs text-slate-500">{student.isMe ? "O seu resultado" : `Lugar ${student.position}`}</p></div></div><span className="inline-flex items-center gap-1 whitespace-nowrap font-display text-xl font-black text-[#0b45ad] dark:text-[#ffd326]"><Award className="h-4 w-4" /> {student.score}%</span></li>)}</ol> : <p className="mt-8 rounded-2xl bg-blue-50 p-5 text-sm text-slate-600 dark:bg-white/5 dark:text-slate-300">Ainda não há resultados nesta turma. Seja o primeiro a concluir o teste.</p>}{data.yourScore !== null && !data.students.some(student => student.isMe) && <p className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900 dark:bg-amber-500/10 dark:text-amber-200">A sua nota: {data.yourScore}%. O destaque mostra os 10 melhores resultados aprovados da turma.</p>}</>}
  </section>;
}
